import Head from "next/head";

import styles from "../styles/Home.module.css";

import Navbar from "../components/Navbar/Navbar";
import Banner from "../components/Banner/Banner";
import SectionCards from "../components/Card/SectionCards";

import { getPopularVideos, getVideos } from "../lib/videos";

export async function getServerSideProps() {
  const disneyVideos = await getVideos("disney%20trailer");
  const travelVideos = await getVideos("travel%20documentary");
  const popularVideos = await getPopularVideos();
  const productivityVideos = await getVideos("productivity");

  return {
    props: { disneyVideos, travelVideos, popularVideos, productivityVideos },
  };
}

export default function Home({
  disneyVideos,
  travelVideos,
  popularVideos,
  productivityVideos,
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar username="djzik3@gmail.com" />
        <Banner
          title="Clifford the Big Red Dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford-the-big-red-dog.webp"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
